# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DuFpgnuiKNmAuOZJbTQUL7QXWU9Nv7LZ
"""

# =====================================================
# DESAFIO HACKER — RSA
# =====================================================

import streamlit as st
import sympy as sp

# =====================================================
# CONFIGURAÇÃO
# =====================================================

st.set_page_config(
    page_title="Desafio Hacker",
    page_icon="🔐",
    layout="centered"
)

# =====================================================
# ESTILO
# =====================================================

st.markdown("""
<style>

.stApp {
    background-color: #000000;
    color: #00BFFF;
}

h1, h2, h3 {
    color: #00BFFF;
}

.stTextInput > div > div > input {
    background-color: #001133;
    color: #FFFFFF;
    border: 1px solid #00BFFF;
}

.stButton > button {
    background-color: #001133;
    color: #00BFFF;
    border: 1px solid #00BFFF;
    border-radius: 10px;
    font-weight: bold;
}

.stButton > button:hover {
    background-color: #002255;
    color: #FFFFFF;
    border: 1px solid #00BFFF;
}

</style>
""", unsafe_allow_html=True)

# =====================================================
# DADOS DO DESAFIO
# =====================================================

E = 3
N = 55

MENSAGEM_CIFRADA = "0x08 0x11"

SENHA_CORRETA = "B8"

# =====================================================
# SESSION STATE
# =====================================================

if "desbloqueado" not in st.session_state:
    st.session_state.desbloqueado = False

if "tentativas" not in st.session_state:
    st.session_state.tentativas = 0

# =====================================================
# CABEÇALHO
# =====================================================

st.title("🔐 DESAFIO HACKER")

st.subheader("💻 Sistema de Segurança — Acesso Restrito")

st.write(
    "Você conseguiu interceptar uma mensagem protegida "
    "por criptografia RSA. O sistema está bloqueado e "
    "a única forma de obter acesso é descobrir a senha."
)

# =====================================================
# HISTÓRIA
# =====================================================

st.markdown("### 🚨 ALERTA DE SEGURANÇA")

st.warning(
    "Uma mensagem criptografada foi interceptada. "
    "O servidor exige a senha correta para liberar o acesso."
)

st.write(
    "Você recebeu apenas a chave pública e a mensagem cifrada em hexadecimal. "
    "Use seus conhecimentos de RSA para descobrir a senha que pode conter números e letras."
)

# =====================================================
# INFORMAÇÕES
# =====================================================

st.markdown("### 🔑 Dados interceptados")

col1, col2 = st.columns(2)

with col1:

    st.markdown("**Chave Pública:**")

    st.latex(
        r"(e,n)=(3,55)"
    )

with col2:

    st.markdown("**Mensagem Cifrada:**")

    st.code(
        "8Q",
        language=None
    )

# =====================================================
# CONVENÇÃO
# =====================================================

st.info(
    "🔤 Convenção utilizada: "
    "A = 1, B = 2, C = 3, ..., Z = 26"
)

# =====================================================
# DESAFIO
# =====================================================

st.markdown("### 🎯 DESAFIO")

st.write(
    "Descubra a senha de acesso a partir da mensagem "
    "cifrada e digite-a abaixo."
)

st.write(
    "A senha é formada pelos símbolos obtidos após "
    "a descriptografia."
)

# =====================================================
# CAMPO DE RESPOSTA
# =====================================================

resposta = st.text_input(
    "🔓 Digite a senha de acesso:",
    max_chars=10,
    placeholder="Digite a senha"
)

# =====================================================
# BOTÃO
# =====================================================

if not st.session_state.desbloqueado:

    if st.button("🚀 DESBLOQUEAR SISTEMA"):

        st.session_state.tentativas += 1

        resposta_normalizada = resposta.strip()

        if resposta_normalizada == SENHA_CORRETA:

            st.session_state.desbloqueado = True

            st.success(
                "✅ SENHA CORRETA!"
            )

            st.balloons()

        else:

            st.error(
                "❌ ACESSO NEGADO — SENHA INCORRETA"
            )

# =====================================================
# SISTEMA DESBLOQUEADO
# =====================================================

if st.session_state.desbloqueado:

    st.markdown("---")

    st.success(
        "🔓 SISTEMA DESBLOQUEADO"
    )

    st.balloons()

    st.markdown(
        """
        ## 🎉 PARABÉNS!

        **Você cumpriu a missão.**

        A mensagem foi descriptografada corretamente,
        a senha de acesso foi recuperada e o sistema
        foi desbloqueado.

        🔐 **ACESSO AUTORIZADO**

        💻 **MISSÃO CONCLUÍDA — AGENTE CRIPTOGRÁFICO**
        """
    )

    st.markdown("---")

    st.info(
        "A segurança do sistema foi restaurada. "
        "Você demonstrou domínio da descriptografia RSA."
    )

# =====================================================
# RODAPÉ
# =====================================================

st.markdown("---")

st.caption(
    "CryptoChallenge • Desafio de Criptografia RSA"
)
